version: '3'
services:
    web:
        image: nginx:latest
        restart: always
        ports:
            - "8300:80"
        volumes:
            - ../:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./log/nginx:/var/log/nginx
        links:
            - php
    php:
        build: ./php
        restart: always
        volumes:
            - ../:/var/www/html
        external_links:
            - mariadb:mariadb

networks:
  default:
    external:
      name: web
