-- MySQL Script generated by MySQL Workbench
-- mer. 19 mai 2021 18:15:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hotelio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotelio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotelio` ;
USE `hotelio` ;

-- -----------------------------------------------------
-- Table `hotelio`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelio`.`user` ;

CREATE TABLE IF NOT EXISTS `hotelio`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelio`.`room_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelio`.`room_type` ;

CREATE TABLE IF NOT EXISTS `hotelio`.`room_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelio`.`room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelio`.`room` ;

CREATE TABLE IF NOT EXISTS `hotelio`.`room` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `room_type_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `picture` VARCHAR(255) NOT NULL DEFAULT '/static/default_room.jpg',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_room_room_type_idx` (`room_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_room_room_type`
    FOREIGN KEY (`room_type_id`)
    REFERENCES `hotelio`.`room_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelio`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelio`.`customer` ;

CREATE TABLE IF NOT EXISTS `hotelio`.`customer` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelio`.`room_booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelio`.`room_booking` ;

CREATE TABLE IF NOT EXISTS `hotelio`.`room_booking` (
  `room_id` INT UNSIGNED NOT NULL,
  `customer_id` INT UNSIGNED NOT NULL,
  `date_min` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_max` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_paid` TINYINT NOT NULL DEFAULT 0,
  INDEX `fk_room_booking_room1_idx` (`room_id` ASC) VISIBLE,
  INDEX `fk_room_booking_customer1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_room_booking_room1`
    FOREIGN KEY (`room_id`)
    REFERENCES `hotelio`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room_booking_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `hotelio`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `hotelio`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `hotelio`;
INSERT INTO `hotelio`.`user` (`id`, `login`, `password`, `email`, `created_at`, `updated_at`) VALUES (1, 'admin', '$2y$10$iaQCHHEHd4g33UeSswZZDeiVPAa6eodgGxv2zv5D6C0mJv0icKAkC', 'admin@admin.fr', DEFAULT, DEFAULT);

COMMIT;

